# docker-compose.yml
version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ~/Desktop/spring_study/grafana-9.3.6/data:/var/lib/grafana
      - ./grafana_provisioning:/etc/grafana/provisioning
      - ./grafana_dashboard:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  k6:
    image: grafana/k6:latest
    container_name: k6
    command: run -o experimental-prometheus-rw /scripts/output_test.js
    volumes:
      - ./output_test.js:/scripts/output_test.js
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
    networks:
      - default
    depends_on:
      - prometheus